# Use an argument for the Node version (default: 20-alpine)
ARG NODE_VERSION=20-alpine
FROM node:${NODE_VERSION} AS base

# Enable Corepack and prepare pnpm (using a supported version, e.g. 8.7.0)
RUN corepack enable && corepack prepare pnpm@8.7.0 --activate

# --- Dependencies Stage ---
FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
# Copy only package files first to leverage Docker cache
COPY package.json pnpm-lock.yaml .npmrc* ./
RUN pnpm i --frozen-lockfile

# --- Build Stage ---
FROM base AS builder
WORKDIR /app
# Copy dependencies and then the rest of the source code
COPY --from=deps /app/node_modules ./node_modules
COPY . .
# (If your build needs any env variables, you can set them here)
RUN pnpm run build

# --- Production (Runner) Stage ---
FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production

# Create a non-root user for better security
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Copy public assets and prepare Next.js output
COPY --from=builder /app/public ./public
RUN mkdir -p .next && chown nextjs:nodejs .next
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Set default (empty) environment variables for runtime.
# These are available when the container starts (but not used during build)
ENV AUTH_SECRET="" \
    AZURE_COMMUNICATION_EMAIL_ENDPOINT="" \
    AZURE_STORAGE_CONNECTION_STRING="" \
    CONTAINER_NAME_AVATARS="" \
    DATABASE_HOST="" \
    DATABASE_NAME="" \
    DATABASE_PASSWORD="" \
    DATABASE_URL="" \
    DATABASE_USER="" \
    EMAIL_FROM="" \
    GOOGLE_CLIENT_ID="" \
    GOOGLE_CLIENT_SECRET="" \
    NEXT_PUBLIC_API_BASE_URL=""

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Switch to non-root user
USER nextjs

# Start the Next.js production server (server.js is generated by the standalone build)
CMD ["node", "server.js"]
