import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  const baseUrl = 'https://www.thebakerz.com'
  
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/about-us',
          '/become-partner',
          '/search',
          '/socials',
          '/support',
          '/support/contact-us',
          '/policies/privacy-policy',
          '/policies/refund-policy',
          '/policies/terms-of-use',
          '/*/',
          '/*/item/*/',
          '/images/',
          '/icons/',
          '/assets/',
          '/_next/static/',
          '/public/',
          '/*mobile$',
          '/*responsive$',
          '/assets/mobile/',
          '/images/mobile/',
          '/*?category=*',
          '/auth',
        ],
        disallow: [
          '/login',
          '/register',
          '/account/',
          '/dashboard/',
          '/admin/',
          '/favorites',
          '/orders',
          '/settings',
          '/profile',
          '/*/checkout',
          '/*/pay/',
          '/*/order/success',
          '/*/order/failed',
          '/cart',
          '/payment',
          '/*/products',
          '/*/settings',
          '/*/orders/',
          '/*/item/add-item',
          '/transit-login',
          '/transit-exit',
          '/api/',
          '/*?*sort=*&*',
          '/*?*filter=*&*',
          '/*?*price=*&*',
          '/*?*color=*&*',
          '/*?*size=*&*',
          '/*?*brand=*&*',
          '/*?*',
          '/*&*',
          '/search?*',
          '/*sort=*',
          '/*filter=*',
          '/*page=*',
          '/*minPrice=*',
          '/*maxPrice=*',
          '/*/item/*/reviews?*',
          '/*/item/*/compare*',
          '/*/products/compare*',
          '/*/search?*',
          '/.well-known/',
          '/robots.txt',
          '/sitemap*.xml',
          '/_next/',
          '/node_modules/',
          '/dev/',
          '/test/',
          '/staging/',
          '/.git/',
          '/*.pdf$',
          '/*.doc$',
          '/*.docx$',
          '/*.xls$',
          '/*.xlsx$',
          '/*.json$',
          '/*.xml$',
          '/*/expired/',
          '/*/out-of-stock/',
        ],
      },
      {
        userAgent: 'Googlebot',
        allow: ['/robots.txt', '/sitemap*.xml', '/api/structured-data'],
      },
      {
        userAgent: 'Bingbot',
        crawlDelay: 2,
      },
      {
        userAgent: 'SemrushBot',
        disallow: ['/'],
      },
      {
        userAgent: 'AhrefsBot',
        disallow: ['/'],
      },
      {
        userAgent: 'MJ12bot',
        disallow: ['/'],
      },
      {
        userAgent: 'DotBot',
        disallow: ['/'],
      },
      {
        userAgent: 'BLEXBot',
        disallow: ['/'],
      },
      {
        userAgent: 'PetalBot',
        disallow: ['/'],
      },
      {
        userAgent: 'YandexBot',
        crawlDelay: 5,
      },
      {
        userAgent: 'facebookexternalhit',
        allow: ['/'],
      },
      {
        userAgent: 'Twitterbot',
        allow: ['/'],
      },
      {
        userAgent: 'LinkedInBot',
        allow: ['/'],
      },
      {
        userAgent: 'WhatsApp',
        allow: ['/'],
      },
      {
        userAgent: 'TelegramBot',
        allow: ['/'],
      },
    ],
    sitemap: [
      `${baseUrl}/sitemap.xml`,
    ],
    host: baseUrl,
  }
} 